### ISSUE TITLE
Compiler Linking Error

### ISSUE THREAD

**Issue by Pecacheu** [xem/3DShomebrew#31]
I'm stuck on `III. b] Hello build !`. The template example had some syntax errors and whatnot that I was able to fix, but now I'm getting this weird error and I can't fix it:
<pre>linking template.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find 3dsx_crt0.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
</pre>
I'm on Windows, and yes, I added DevKitPro and Python3 to PATH.

**Comment by xem** [comment]
Oh... sorry, I've let the community edit the wiki pages freely, and I don't know how to fix that error.
I recommend you this forum instead: https://gbatemp.net/forums/3ds-homebrew-development-and-emulators.275/

**Comment by Pecacheu** [comment]
Oops, I forgot I opened this. I solved my problem a few days ago. It was that the Makefile from the hello example was old and didn't work with the current version of DevKitARM. The Makefile from one of the included examples did the trick.

Also, you should add a link to the official ctrulib documentation at http://smealum.github.io/ctrulib. It took me a while to find it.
